"""
Signal journal — append-only JSONL store linking signals to outcomes.

Every signal generated by scanner is recorded with full entry context.
Outcomes (TARGET_HIT / SL_HIT / EXPIRED) are resolved later by
signal_tracker.py (price monitoring) or manually via Streamlit.

Schema per record:
  signal_id   : str  — "{symbol}_{date}_{seq}"
  symbol, direction, entry_price, sl_price, target_price
  patterns    : list[str]
  vote_margin : int   (long_votes - short_votes, absolute)
  rsi         : float
  volume_ratio: float
  market_bias : str
  session     : str
  volatility  : str
  rank        : int
  score       : float
  ai_prob     : float
  ts          : ISO str — signal generation time
  --- option fields (null when chain unavailable at entry time) ---
  option_strike : float | null
  option_expiry : str   | null  (YYYY-MM-DD)
  option_type   : str   | null  ("CE" | "PE")
  entry_prem    : float | null  (ATM CE/PE LTP or BSM theoretical)
  sl_prem       : float | null  (premium level to exit at loss)
  target_prem   : float | null  (premium level to exit at profit)
  delta         : float | null  (BSM delta at entry)
  iv_pct        : float | null  (IV % used for pricing)
  prem_source   : str   | null  ("live" = Dhan LTP | "theoretical" = BSM)
  exit_prem     : float | null  (actual premium at exit — set on resolve)
  --- resolution fields ---
  outcome     : null | "TARGET_HIT" | "SL_HIT" | "EXPIRED"
  exit_price  : null | float  (spot price at exit)
  exit_ts     : null | ISO str
  pnl_rupees  : null | float  (premium P&L when option fields present, else spot P&L)
"""

from __future__ import annotations

import json
import os
import threading
from datetime import datetime, date
from typing import Dict, List, Optional

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JOURNAL_FILE = os.path.join(_PROJECT_ROOT, "logs", "signal_journal.jsonl")

_lock = threading.Lock()
_seq_counters: Dict[str, int] = {}


def _make_signal_id(symbol: str) -> str:
    today = date.today().isoformat()
    key = f"{symbol}_{today}"
    _seq_counters[key] = _seq_counters.get(key, 0) + 1
    return f"{symbol}_{today}_{_seq_counters[key]:03d}"


def record_signal(signal: Dict) -> str:
    """Write a new signal record with outcome=null. Returns signal_id."""
    os.makedirs(os.path.dirname(JOURNAL_FILE), exist_ok=True)

    patterns_raw = signal.get("patterns_combined", "") or signal.get("reason", "")
    if isinstance(patterns_raw, str):
        patterns = [p.strip() for p in patterns_raw.replace("|", ",").split(",") if p.strip()]
    else:
        patterns = list(patterns_raw)

    sym = signal.get("symbol", "UNKNOWN")
    direction = signal.get("direction", "")
    today = date.today().isoformat()

    # Deduplicate: only 1 open signal per (symbol, direction, date).
    # Scanner runs every 30s; without this we'd get 720 identical entries/day.
    with _lock:
        if os.path.exists(JOURNAL_FILE):
            existing = _load_all()
            for r in existing:
                if (r.get("symbol") == sym
                        and r.get("direction") == direction
                        and r.get("outcome") is None
                        and r.get("ts", "")[:10] == today):
                    return r["signal_id"]  # already tracking this signal

    signal_id = _make_signal_id(sym)

    def _opt_float(v) -> Optional[float]:
        try:
            f = float(v)
            return round(f, 6) if f else None
        except (TypeError, ValueError):
            return None

    record = {
        "signal_id":    signal_id,
        "symbol":       sym,
        "direction":    direction,
        "entry_price":  float(signal.get("entry_price", 0)),
        "sl_price":     float(signal.get("sl_price", 0)),
        "target_price": float(signal.get("target_price", 0)),
        "patterns":     patterns,
        "vote_margin":  int(signal.get("vote_margin", 0)),
        "rsi":          float(signal.get("rsi", 50)),
        "volume_ratio": float(signal.get("volume_ratio", 1.0)),
        "market_bias":  signal.get("market_bias", "neutral"),
        "session":      signal.get("session", "unknown"),
        "volatility":   str(signal.get("volatility", "NORMAL")),
        "rank":         int(signal.get("rank", 0)),
        "score":        float(signal.get("confluence_score", signal.get("score", 0))),
        "ai_prob":      float(signal.get("ai_probability", signal.get("ai_prob", 0.5))),
        "grade":        signal.get("confluence_grade", "C"),
        "ts":           signal.get("ts", datetime.now().isoformat()),
        # option leg fields (None when chain unavailable at signal-gen time)
        "option_strike": _opt_float(signal.get("option_strike")),
        "option_expiry": signal.get("option_expiry", None),
        "option_type":   signal.get("option_type", None),
        "entry_prem":    _opt_float(signal.get("entry_prem")),
        "sl_prem":       _opt_float(signal.get("sl_prem")),
        "target_prem":   _opt_float(signal.get("target_prem")),
        "delta":         _opt_float(signal.get("delta")),
        "iv_pct":        _opt_float(signal.get("iv_pct")),
        "prem_source":   signal.get("prem_source", None),
        # resolution fields
        "outcome":      None,
        "exit_price":   None,
        "exit_prem":    None,
        "exit_ts":      None,
        "pnl_rupees":   None,
    }

    with _lock:
        with open(JOURNAL_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")

    return signal_id


def resolve_signal(signal_id: str, outcome: str,
                   exit_price: float, exit_ts: Optional[str] = None,
                   lot_size: int = 1, exit_prem: Optional[float] = None) -> bool:
    """
    Resolve a signal outcome. Rewrites the JSONL line in-place.
    outcome: "TARGET_HIT" | "SL_HIT" | "EXPIRED"
    exit_prem: option premium at exit — when provided and record has entry_prem,
               pnl_rupees is computed from premium move (option P&L), not spot move.
    """
    if not os.path.exists(JOURNAL_FILE):
        return False

    with _lock:
        records = _load_all()
        updated = False
        for r in records:
            if r.get("signal_id") == signal_id and r.get("outcome") is None:
                entry_prem = r.get("entry_prem")
                if entry_prem and exit_prem is not None:
                    # Option P&L: always from buyer perspective (prem goes up = profit)
                    pnl = (exit_prem - float(entry_prem)) * lot_size
                    r["exit_prem"] = round(exit_prem, 2)
                else:
                    direction = r.get("direction", "long")
                    entry = float(r.get("entry_price", 0))
                    if entry > 0 and lot_size > 0:
                        if direction == "long":
                            pnl = (exit_price - entry) * lot_size
                        else:
                            pnl = (entry - exit_price) * lot_size
                    else:
                        pnl = 0.0
                r["outcome"]    = outcome
                r["exit_price"] = exit_price
                r["exit_ts"]    = exit_ts or datetime.now().isoformat()
                r["pnl_rupees"] = round(pnl, 2)
                updated = True
                break

        if updated:
            _write_all(records)

    return updated


def resolve_by_symbol_entry(symbol: str, entry_approx: float, outcome: str,
                             exit_price: float, lot_size: int = 1,
                             tolerance_pct: float = 0.02) -> bool:
    """Fuzzy-match: find latest OPEN signal for symbol near entry_approx and resolve it."""
    if not os.path.exists(JOURNAL_FILE):
        return False

    with _lock:
        records = _load_all()
        candidates = [
            r for r in records
            if r.get("symbol") == symbol
            and r.get("outcome") is None
            and abs(float(r.get("entry_price", 0)) - entry_approx) / max(entry_approx, 1) <= tolerance_pct
        ]
        if not candidates:
            return False
        # pick most recent
        candidates.sort(key=lambda x: x.get("ts", ""), reverse=True)
        target = candidates[0]
        return resolve_signal(target["signal_id"], outcome, exit_price,
                               lot_size=lot_size)


def get_open_signals() -> List[Dict]:
    """Return all signals with outcome=null, ordered oldest first."""
    if not os.path.exists(JOURNAL_FILE):
        return []
    records = _load_all()
    return [r for r in records if r.get("outcome") is None]


def get_resolved_signals(days: int = 90) -> List[Dict]:
    """Return resolved signals from last N days."""
    if not os.path.exists(JOURNAL_FILE):
        return []
    cutoff = None
    if days:
        from datetime import timedelta
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
    records = _load_all()
    return [
        r for r in records
        if r.get("outcome") is not None
        and (cutoff is None or r.get("ts", "") >= cutoff)
    ]


def get_all_signals(days: int = 90) -> List[Dict]:
    if not os.path.exists(JOURNAL_FILE):
        return []
    cutoff = None
    if days:
        from datetime import timedelta
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
    records = _load_all()
    return [r for r in records if cutoff is None or r.get("ts", "") >= cutoff]


def _load_all() -> List[Dict]:
    records = []
    try:
        with open(JOURNAL_FILE, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        records.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
    except Exception:
        pass
    return records


def _write_all(records: List[Dict]) -> None:
    tmp = JOURNAL_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")
    os.replace(tmp, JOURNAL_FILE)
