"""Shared F&O universe used by runner, scanner, and dashboards."""

FO_UNIVERSE = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK",
    "SBIN", "BHARTIARTL", "KOTAKBANK", "BAJFINANCE", "HINDUNILVR",
    "ITC", "LT", "AXISBANK", "MARUTI", "ASIANPAINT",
    "WIPRO", "HCLTECH", "TITAN", "SUNPHARMA", "TATAMOTORS",
    "ADANIENT", "NTPC", "POWERGRID", "ULTRACEMCO", "JSWSTEEL",
    "ONGC", "COALINDIA", "BPCL", "HEROMOTOCO", "EICHERMOT",
    "TATASTEEL", "HINDALCO", "GRASIM", "CIPLA", "DIVISLAB",
    "DRREDDY", "BRITANNIA", "NESTLEIND", "TATACONSUM", "M&M",
    "BAJAJ-AUTO", "INDUSINDBK", "TECHM", "ADANIPORTS", "BAJAJFINSV",
    "HDFCLIFE", "LTIM", "SHRIRAMFIN", "TRENT", "APOLLOHOSP",
    "ABB", "ALKEM", "AMBUJACEM", "APOLLOTYRE", "AUROPHARMA",
    "BANDHANBNK", "BANKBARODA", "BEL", "BERGEPAINT", "BHARATFORG",
    "BHEL", "BIOCON", "BOSCHLTD", "CANBK", "CEATLTD",
    "CHOLAFIN", "COLPAL", "CONCOR", "COROMANDEL", "DABUR",
    "DLF", "DMART", "ESCORTS", "EXIDEIND", "FEDERALBNK",
    "GAIL", "GLENMARK", "GODREJCP", "GODREJPROP", "GRANULES",
    "GUJGASLTD", "HAVELLS", "HINDPETRO", "ICICIPRULI", "ICICIGI",
    "IDFCFIRSTB", "IGL", "INDHOTEL", "INDIGO", "INDUSTOWER",
    "IPCALAB", "IRCTC", "IRFC", "JINDALSTEL", "JIOFIN",
    "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LICI",
    "LUPIN", "M&MFIN", "MANAPPURAM", "MARICO", "MAXHEALTH",
    "MCX", "METROPOLIS", "MCDOWELL-N", "MOTHERSON", "MPHASIS",
    "MUTHOOTFIN", "NATIONALUM", "NAUKRI", "NCC", "NHPC",
    "NMDC", "NYKAA", "OBEROIRLTY", "OFSS", "OLECTRA",
    "PAGEIND", "PAYTM", "PFC", "PIIND",
    "PNB", "POLYCAB", "PVRINOX", "RAMCOCEM", "RECLTD",
    "SAIL", "SBICARD", "SBILIFE", "SHREECEM", "SIEMENS",
    "SUNTV", "TATACOMM", "TATACHEM", "TATAELXSI", "TATAPOWER",
    "TVSMOTOR", "UBL", "UPL", "VEDL", "VOLTAS",
    "ETERNAL", "ZYDUSLIFE", "ADANIGREEN", "ADANIPOWER",
    "ATUL", "BALKRISIND", "DEEPAKNTR", "NAVINFLUOR", "PERSISTENT",
    "PIDILITIND",
]

# Most-liquid 100 F&O names (FO_UNIVERSE is rank-ordered largest→smallest by
# market-cap / turnover). Tighter universe = less noise, tighter spreads,
# cleaner option chains. Scanner uses this by default.
TOP100_FO = FO_UNIVERSE[:100]
